### ISSUE TITLE
Infinite scrolling

### ISSUE THREAD

**Issue by ShadeApps** [zammitjames/JZStackedView#3]
Thanks for a great control! 

What things do we need to add to make it infinitely scrollable? Would it require some hard work?

**Comment by zammitjames** [comment]
Just set the property wrapEnabled to TRUE, and it will scroll infinitely :)

**Comment by ShadeApps** [comment]
Thanks! It worked :)
It's strange though that it's designed in the way that it's a readonly property and you have to change it inside the class. I understand though that it's safer if someone tries to change it sometime after the setup, though.
